[package]
name = "anytls-rs"
version = "0.2.0"
edition = "2024"
authors = ["anytls-rs contributors"]
description = "A proxy protocol that attempts to mitigate the TLS in TLS fingerprinting problem"
license = "MIT"
repository = "https://github.com/ssrlive/anytls-rs"
keywords = ["proxy", "tls", "privacy", "networking"]
categories = ["network-programming", "command-line-utilities"]

[[bin]]
name = "anytls-client"
path = "src/bin/client.rs"

[[bin]]
name = "anytls-server"
path = "src/bin/server.rs"

[dependencies]
async-trait = "0.1.89"
base64 = "0.22.1"
bytes = "1.11.1"
clap = { version = "4.6.1", features = ["derive", "cargo"] }
dashmap = "6.1.0"
env_logger = "0.11.10"
futures = "0.3.32"
hex = "0.4.3"
indexmap = "2.14.0"
log = "0.4.29"
md5 = "0.8.0"
parking_lot = "0.12.5"
rand = "0.10.1"
rcgen = "0.14.7"
rustls = "0.23.39"
rustls-pemfile = "2.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
socket2 = "0.6.3"
socks5-impl = { version = "0.8.1", features = ["server"] }
thiserror = "2.0.18"
tokio = { version = "1.52.1", features = ["full"] }
tokio-rustls = "0.26.4"
url = "2.5.8"
x509-parser = "0.18.1"
